# Generated by Django 5.1.2 on 2025-10-28 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
